### ISSUE TITLE
Problem with localhost

### ISSUE THREAD

**Issue by vtabashniuk** [dev5c32373043/parcel-reporter-clean-dist#6]
After installation of this plugin, my project has builded, but... localhost refused connection.
If I uninstall it, localhost work normally.
Have no idea
![2021-12-25](https://user-images.githubusercontent.com/60541362/147391830-8c951d7b-9f37-4d94-846a-a6a56365b62a.png)
![2021-12-25 (1)](https://user-images.githubusercontent.com/60541362/147391839-a0d75fd6-365c-44b6-8730-35a55f024f9f.png)
.

**Comment by dev5c32373043** [comment]
@vtabashniuk it seems you forgot to add `@parcel/reporter-dev-server` reporter to the config
i.e the config should be looking something like that:
`{
    "extends": ["@parcel/config-default"],
    "reporters": ["@parcel/reporter-dev-server", "parcel-reporter-clean-dist"]
}`

**Comment by vtabashniuk** [comment]
@dev5c32373043  thanks. That's it!
May be you will add this config at Configuration part of Readme.

**Comment by dev5c32373043** [comment]
@vtabashniuk yeah, good thought, I'll consider adding this kind of information into the readme within a next release
